services:
  e2e-chrome:
    container_name: cypress-docker-e2e-chrome
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cypress/docker:v1
    command: '--browser chrome'
    env_file:
      - ./cypress-secrets.env
    volumes:
      - .:/cypress-docker
      - test-report-e2e-chrome:/report
      - /cypress-docker/node_modules

  #####################################
  smoke-chrome:
    container_name: cypress-docker-smoke-chrome
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cypress/docker:v1
    command: '--browser chrome --env grepTags=@smoke,grepFilterSpecs=true'
    env_file:
      - cypress-secrets.env
    volumes:
      - .:/cypress-docker
      - test-report-smoke-chrome:/report
      - /cypress-docker/node_modules

  #####################################
  regression-chrome:
    container_name: cypress-docker-regression-chrome
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cypress/docker:v1
    command: '--browser chrome --env grepTags=@regression,grepFilterSpecs=true'
    env_file:
      - cypress-secrets.env
    # environment:
    #  - DEBUG=cypress:server:browsers:chrome,cypress:server:util:process_profiler
    volumes:
      - .:/cypress-docker
      - test-report-reggression-chrome:/report
      - /cypress-docker/node_modules

  #####################################
volumes:
  test-report-e2e-chrome:
  test-report-smoke-chrome:
  test-report-reggression-chrome:
