#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# https://github.com/desktop/desktop/issues/12562
# bug on Windows/Github Desktop: add `.cmd` extension fixes it
case `uname` in  
  *CYGWIN*|*MINGW*|*MSYS*)
  npx.cmd lint-staged
  ;;
  *)
  npx lint-staged
  ;;
esac