name: Test

on:
  push:
    branches:
    - main
    - test
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.2
      with:
        compose-file: "./docker-compose.dev.yml"
