name: Docker Compose Action

on:
  push:
    branches:
    - main
    - test
    - test/**
    - features/**
    # - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run docker-compose
      uses: adambirds/docker-compose-action@v1.5.0
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      with:
        compose-file: "./docker-compose.dev.yml"
        up-flags: "--build -d"
        # down-flags: "--volumes"
    
