name: Docker Compose Action

on:
  push:
    branches:
      - main
      - test
      - test/**
      - features/**
  pull_request:
    branches:
      - main

jobs:
  smoke-tests-dev:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    environment:
      name: development

    name: smoke-tests-dev
    steps:
      - uses: actions/checkout@v4

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: './docker-compose.dev.yml'
          up-flags: '--build -d'
          down-flags: '--volumes'
          test-container: 'smoke-chrome'
          test-command: 'yarn run tsc:build'
        env:
          # Set up the Cypress Cloud project ID and record key as environment variables
          # If the Actions secret EXAMPLE_PROJECT_ID is not defined then
          # the projectId is taken from cypress.json (v9) or cypress.config.js (v10 and later).
          # If the Actions secret EXAMPLE_RECORDING_KEY is not defined then recording jobs are skipped.
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
