name: Docker Compose Action

on:
  push:
    branches:
      - main
      - test
      - test/**
      - features/**
  pull_request:
    branches:
      - main

jobs:
  smoke-tests-dev:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    environment:
      name: development

    name: smoke-tests-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          install-command: yarn install
          command: yarn run cy:run --browser chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_grepFilterSpecs: true
          CYPRESS_grepTags: '@api'
          CYPRESS_grepOmitFiltered: true
